### PR TITLE
huge refactor

### PR DESCRIPTION
**Pull request by Ferdydh**
Changed name
- ChatGPT -> Assistant
- openai -> execute
- SimpleHistory -> MesssageHistory

Removed:
- Extra class from Assistant
- Extra class from MessageHistory

Factored out:
-  the model selection in openai.py
- the events to their own classes (instead of nested classes)

We can discuss:
-  what to name Model instead
- If we want to keep the name ChatGPT (or my suggestion: assistant)

Feel free to check this PR when you have time XP

### CODE REVIEW

**Comment by Ferdydh** [comment]
And petition to change the name to assistant 😅 hope you dont mind my many inteferring & inquiries

**Comment by JoongWonSeo** [comment]
While I didn't have time to fully look into every detail, there are a lot of changes in here that I always wanted to make as well, along with some much needed sustainable solution for supporting various alternative clients! I'd definitely want to take advantage of this to make all the breaking changes I've had in mind to minimize migration issues.

I will still need a few days to look into the details and experiment with potentially alternative designs (esp. for the API part), but this is definitely in the right direction, I think :)

There's also a few more things we need to discuss, let's maybe take a bit of time end of this week to work on it together?

**Comment by JoongWonSeo** [comment]
Some topics we need to discuss before I forget (more like a note to self):
- API: openai -> executer naming, note that even with alternative clients, the API itself (the interface) is the OpenAI API (they are the source of truth), but there are some competing APIs (e.g. google) so depending on future direction, might want to keep it explicitly openai here.
- Removing `model` from `openai_kwargs`: The original idea was that it would be identical to what you'd pass to the raw `openai` api... this would be a departure from that
- Mocking design might need to be slightly redesigned, esp. regarding recording (right now its at API-level but might make more sense at Assistant level), also for potential cached response support
- Events global vs nested: discuss w.r.t. import, overriding, etc.
- MessageHistory might want to shorten even further to just Messages?

Other (unrelated) todos:
- Split dependencies into subgroups for optional features like for RAG, alternative LLM providers, etc while keeping the base package lightweight
- Better documentation (still use pdoc? or move to mkdocs?)
- ...

**Comment by Ferdydh** [comment]
Great, let's talk about this on saturday when we meet?

Also some more points to discuss/note:
- Currently, the jupyter notebook is somewhat faulty
- Is there a LLM-enabled easy documentations? Sounds like an interesting topic to pursue XD (as if we don't have enough things to work on lol)
- It'd be nice to have explicit types (e.g. for model names) so we can be sure which ones are available

**Pull request closed without merging**
